### ISSUE TITLE
Extended Winning Conditions Bug: Multitasking armies

### ISSUE THREAD

**Issue by ArtieZ** [dabo123148/WarlightMod#17] opened 2019-04-05 19:46 UTC
I created a single player game to develop into a multiplayer scenario.  While testing it, I had 21 armies to attempt taking two neutral territories, with modified kill rates.  The first attack on "Young" with ten armies failed (I lost four, returning six to Canberra).  The second attack on "Wagga Wagga" was with the full 100% of the remaining armies (supposed to be 11 armies).  However, the six surviving armies from the attack on Young also participated in the attack on Wagga Wagga.  Thanks, LeBorgne
See attached files.
![Multitasking armies](https://user-images.githubusercontent.com/12702812/55652545-bcd2ab00-57b9-11e9-9598-5ebeb83c2cf0.gif)
![Screen Shot 2019-04-05 at 3 06 52 PM](https://user-images.githubusercontent.com/12702812/55652553-c78d4000-57b9-11e9-875d-9db0918729aa.png)
![Screen Shot 2019-04-05 at 3 07 08 PM](https://user-images.githubusercontent.com/12702812/55652554-c78d4000-57b9-11e9-91be-7a6afac0a2a2.png)
![Screen Shot 2019-04-05 at 3 35 24 PM](https://user-images.githubusercontent.com/12702812/55652556-c78d4000-57b9-11e9-81aa-b785d5c90a12.png)

**Comment by dabo123148** [comment] 2019-04-05 19:56
ok, that is strange since I do not change any orders, but , I will take a look into it

**Comment by dabo123148** [comment] 2019-04-05 20:13
I am having problems with reproducing the bug, can you maybe send me what your original orders were and where you were playing warzone as well as the version if it was not the latest

**Comment by dabo123148** [comment] 2019-04-05 20:19
actually I managed to reproduce it, but it seems to be a warzone bug and not of the mod, I will report it

**Comment by dabo123148** [comment] 2019-04-06 19:41
This is not a bug:

That is expected in multi-attack. Multi-attack means that each army can do as many attacks as it would like. It's only stopped if it does a transfer, and in this case those armies never transferred, so they can keep attacking.

**Closed as completed by dabo123148** 2019-04-06 19:41 UTC
